"""add podgroup 2

Revision ID: a1bb4c7c08c4
Revises: d974530cfc43
Create Date: 2025-08-27 16:48:07.836441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1bb4c7c08c4'
down_revision: Union[str, None] = 'd974530cfc43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dayboard', sa.Column('podgroup', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dayboard', 'podgroup')
    # ### end Alembic commands ###
