"""init 2

Revision ID: ac02c9118eb0
Revises: b4f10353cfe5
Create Date: 2025-08-25 17:22:59.524636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac02c9118eb0'
down_revision: Union[str, None] = 'b4f10353cfe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dayboard', sa.Column('place_id', sa.Integer(), nullable=False))
    op.add_column('dayboard', sa.Column('type_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('dayboard_place_fkey'), 'dayboard', type_='foreignkey')
    op.drop_constraint(op.f('dayboard_type_fkey'), 'dayboard', type_='foreignkey')
    op.create_foreign_key(None, 'dayboard', 'types', ['type_id'], ['id'])
    op.create_foreign_key(None, 'dayboard', 'places', ['place_id'], ['id'])
    op.drop_column('dayboard', 'place')
    op.drop_column('dayboard', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dayboard', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('dayboard', sa.Column('place', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dayboard', type_='foreignkey')
    op.drop_constraint(None, 'dayboard', type_='foreignkey')
    op.create_foreign_key(op.f('dayboard_type_fkey'), 'dayboard', 'types', ['type'], ['id'])
    op.create_foreign_key(op.f('dayboard_place_fkey'), 'dayboard', 'places', ['place'], ['id'])
    op.drop_column('dayboard', 'type_id')
    op.drop_column('dayboard', 'place_id')
    # ### end Alembic commands ###
